// Hand-drawn pixel art. Each sprite is a grid of palette keys; '.' is transparent.
// Rendered with react-native-svg by <Sprite />, so they stay razor sharp at any scale.

export const PALETTE: Record<string, string> = {
  k: '#000000',
  w: '#FFFFFF',
  y: '#FCD800',
  Y: '#AC7C00',
  o: '#FC9838',
  b: '#C84C0C',
  d: '#6E2A0A',
  r: '#E52521',
  R: '#A00000',
  g: '#00A800',
  l: '#80D010',
  G: '#005800',
  u: '#0058F8',
  c: '#3CBCFC',
  C: '#007C8C',
  s: '#FFC9A0',
  S: '#D9875A',
  p: '#F878F8',
  P: '#C2399A',
  n: '#BCBCBC',
  N: '#6C6C6C',
  v: '#8A4CFC',
  V: '#4B1FA8',
  h: '#503000',
};

export const SPRITES = {
  coin: [
    '..kkkk..',
    '.kyyyyk.',
    'kyywyyok',
    'kyywyyok',
    'kyywyyok',
    'kyywyyok',
    'kyywyyok',
    'kyyyyyok',
    '.kooook.',
    '..kkkk..',
  ],
  hero: [
    '...kkkkk....',
    '..kccccck...',
    '.kcccyccckk.',
    '.kCCCCCCCCCk',
    '.khhssskssk.',
    '.khsssssssk.',
    '..kssSSSsk..',
    '...kssssk...',
    '..kooooook..',
    '.ksoooooosk.',
    '.ksoooooosk.',
    '..kddyyddk..',
    '..kNNNNNNk..',
    '..kNNkkNNk..',
    '.kddk..kddk.',
    '.kkkk..kkkk.',
  ],
  heroJump: [
    '.k.kkkkk..k.',
    'ksckccccckck',
    'ksccccyccckk',
    '.kCCCCCCCCCk',
    '..khssskssk.',
    '..khsssssk..',
    '...kssSSk...',
    '..kooooook..',
    '..kooooook..',
    '..koooooook.',
    '..kddyyddk..',
    '.kNNNkkNNNk.',
    'kddk....kddk',
    'kkk......kkk',
  ],
  heart: ['.kk.kk.', 'krrkrrk', 'kwrrrrk', '.krrrk.', '..krk..', '...k...'],
  star: [
    '....k....',
    '...kyk...',
    '...kyk...',
    'kkkyyykkk',
    '.kyyyyyk.',
    '..kyyyk..',
    '.kyykyyk.',
    '.kyk.kyk.',
    '.kk...kk.',
  ],
  flag: [
    '.kk......',
    'kyyk.....',
    '.kkkkkk..',
    '.nkgwggk.',
    '.nkgggggk',
    '.nkggggk.',
    '.nkkkkk..',
    '.n.......',
    '.n.......',
    '.n.......',
    'kkk......',
  ],
  boss: [
    '....kkkk....',
    '..kkvvvvkk..',
    '.kvvvvvvvvk.',
    '.kvkkvvkkvk.',
    'kvvwkvvkwvvk',
    'kvvwkvvkwvvk',
    'kvvvvvvvvvvk',
    'kvkwkwkwkwvk',
    'kvvkkkkkkvvk',
    '.kVVVVVVVVk.',
    '..kkkkkkkk..',
  ],
  piggy: [
    '....kkkk....',
    '..kkpkkpkk..',
    '.kpppppppppk',
    'kppppppkppkk',
    'kpppppppPPPk',
    'kpppppppPkPk',
    '.kpppppppppk',
    '..kpk..kpk..',
    '..kkk..kkk..',
  ],
  castle: [
    'kkk.kkkk.kkk',
    'knk.knnk.knk',
    'knkkknnkkknk',
    'knnnnnnnnnnk',
    'knNnnnnnnNnk',
    'knnnnkknnnnk',
    'knnnkkkknnnk',
    'knNnkddknNnk',
    'knnnkddknnnk',
    'knnnkddknnnk',
    'kkkkkkkkkkkk',
  ],
  chest: [
    '.kkkkkkkk.',
    'kbybbbbybk',
    'kbybbbbybk',
    'kkkkyykkkk',
    'kbbbyybbbk',
    'kbybbbbybk',
    'kbybbbbybk',
    'kkkkkkkkkk',
  ],
  gem: ['.kkkkk.', 'kcwccuk', 'kccccuk', '.kccuk.', '..kuk..', '...k...'],
  scroll: [
    '.kkkkkkkk.',
    'kowwwwwwok',
    'kowkkkkwok',
    'kowwwwwwok',
    'kowkkkwwok',
    'kowwwwwwok',
    'kowkkkkwok',
    '.kkkkkkkk.',
  ],
  house: [
    '....k....',
    '...krk...',
    '..krrrk..',
    '.krrrrrk.',
    'kkkkkkkkk',
    '.kwwwwwk.',
    '.kwkwkbk.',
    '.kwwwkbk.',
    '.kkkkkkk.',
  ],
  book: [
    '.kkkkkkk.',
    'kuuuuuuk.',
    'kuwwwwuk.',
    'kuuuuuuk.',
    'kuuuuuuk.',
    'kuuuuuukk',
    'kwwwwwwwk',
    '.kkkkkkk.',
  ],
  shield: [
    'kkkkkkkkk',
    'kuuuyuuuk',
    'kuuuyuuuk',
    'kyyyyyyyk',
    'kuuuyuuuk',
    'kuuuyuuuk',
    '.kuuyuuk.',
    '..kuyuk..',
    '...kyk...',
    '....k....',
  ],
  fire: [
    '...k...',
    '..kok..',
    '.kook..',
    '.koork.',
    'korrok.',
    'korrrok',
    'koryrok',
    'kooyook',
    '.kkkkk.',
  ],
  sword: [
    '.......kk',
    '......kwk',
    '.....kwk.',
    '....kwk..',
    'k..kwk...',
    'kkkwk....',
    '.kyk.....',
    'kykkk....',
    'kk.......',
  ],
  cloud: [
    '......kkkk......',
    '....kkwwwwkk....',
    '..kkwwwwwwwwkk..',
    '.kwwwwwwwwwwwwk.',
    'kwwwwwwwwwwwwwwk',
    'kwwcwwwwwwwwcwwk',
    '.kwwccwwwwccwwk.',
    '..kkkkkkkkkkkk..',
  ],
  bolt: ['...kkk.', '..kyyk.', '..kyk..', '.kyyk..', '.kyykkk', 'kyyyyyk', 'kkkyyk.', '..kyk..', '.kyk...', '.kk....'],
  bank: [
    '.....k.....',
    '...kkykk...',
    '.kkyyyyykk.',
    'kkkkkkkkkkk',
    'kwk.kwk.kwk',
    'kwk.kwk.kwk',
    'kwk.kwk.kwk',
    'kkkkkkkkkkk',
    'knnnnnnnnnk',
    'kkkkkkkkkkk',
  ],
  trophy: [
    'kkkkkkkkk',
    'kyywyyyyk',
    'kyywyyyyk',
    '.kywyyyk.',
    '..kyyyk..',
    '...kyk...',
    '...kyk...',
    '..kYYYk..',
    '.kkkkkkk.',
  ],
  crown: ['k...k...k', 'kk.kyk.kk', 'kykyyykyk', 'kyyyryyyk', 'kyyyyyyyk', 'kkkkkkkkk'],
  bubble: [
    '.kkkkkkkk.',
    'kwwwwwwwwk',
    'kwwkwkwkwk',
    'kwwwwwwwwk',
    '.kkwkkkkk.',
    '..kwk.....',
    '..kk......',
  ],
  card: [
    '.kkkkkkkkkk.',
    'kuuuuuuuuuuk',
    'kkkkkkkkkkkk',
    'kuuuuuuuuuuk',
    'kuyyuuuuuuuk',
    'kuyyuuwwwwuk',
    'kuuuuuuuuuuk',
    '.kkkkkkkkkk.',
  ],
  pipe: [
    'kkkkkkkkkk',
    'klggggggGk',
    'klggggggGk',
    'kkkkkkkkkk',
    '.klgggGGk.',
    '.klgggGGk.',
    '.klgggGGk.',
    '.klgggGGk.',
    '.klgggGGk.',
    '.kkkkkkkk.',
  ],
  potion: ['.kkkkk.', '..knk..', '..knk..', '.kpppk.', 'kpwpppk', 'kpppppk', 'kppPPpk', '.kpppk.', '..kkk..'],
  wallet: [
    '.kkkkkkkk..',
    'kbbbbbbbbk.',
    'kkkkkkkkkkk',
    'kbbbbbbkkkk',
    'kbbbbbbkyyk',
    'kbbbbbbkkkk',
    'kbbbbbbbbk.',
    '.kkkkkkkkk.',
  ],
  gift: [
    '.kk...kk.',
    'krrk.krrk',
    '.kkrkrkk.',
    'kkkkkkkkk',
    'kgggrgggk',
    'kgggrgggk',
    'kgggrgggk',
    'kgggrgggk',
    'kkkkkkkkk',
  ],
  gear: [
    '...kkk...',
    '.kkknkkk.',
    '.knnnnnk.',
    'kknk.knkk',
    'knk...knk',
    'kknk.knkk',
    '.knnnnnk.',
    '.kkknkkk.',
    '...kkk...',
  ],
  lock: ['.kkkkk.', 'kk...kk', 'k.....k', 'kkkkkkk', 'kyyyyyk', 'kyykyyk', 'kyykyyk', 'kyyyyyk', 'kkkkkkk'],
} as const;

export type SpriteName = keyof typeof SPRITES;
